// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sistema_academia.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Aluno", b =>
                {
                    b.Property<string>("CpfAluno")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailAluno")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefoneAluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CpfAluno");

                    b.HasIndex("EmailAluno")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Exercicio", b =>
                {
                    b.Property<int>("IdExercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExercicio"));

                    b.Property<int>("Descanso")
                        .HasColumnType("int");

                    b.Property<string>("NomeExercicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("IdExercicio");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("Matricula", b =>
                {
                    b.Property<int>("idMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idMatricula"));

                    b.Property<string>("CpfAluno")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.Property<string>("SituacaoPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("idMatricula");

                    b.HasIndex("CpfAluno")
                        .IsUnique();

                    b.HasIndex("IdPlano");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<int>("IdMatricula")
                        .HasColumnType("int");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPagamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdMatricula");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Plano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("NomePlano")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPlano")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("ValorPlano")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlano");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("Treino", b =>
                {
                    b.Property<int>("idTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idTreino"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("duracaoTreino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idTreino");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("TreinoAluno", b =>
                {
                    b.Property<string>("CpfAluno")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.HasKey("CpfAluno", "IdTreino");

                    b.HasIndex("IdTreino");

                    b.ToTable("TreinoAluno");
                });

            modelBuilder.Entity("TreinoExercicio", b =>
                {
                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.Property<int>("IdExercicio")
                        .HasColumnType("int");

                    b.HasKey("IdTreino", "IdExercicio");

                    b.HasIndex("IdExercicio");

                    b.ToTable("TreinoExercicio");
                });

            modelBuilder.Entity("Matricula", b =>
                {
                    b.HasOne("Aluno", "Aluno")
                        .WithOne()
                        .HasForeignKey("Matricula", "CpfAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Pagamento", b =>
                {
                    b.HasOne("Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("IdMatricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("TreinoAluno", b =>
                {
                    b.HasOne("Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("CpfAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("TreinoExercicio", b =>
                {
                    b.HasOne("Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("IdExercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });
#pragma warning restore 612, 618
        }
    }
}
